# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false
    properties:
      # http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20
    generate-ddl: false
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    # tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    username: user
    password: password
  h2.console.enabled: true
  flyway:
    locations: classpath:db/migration
    url: jdbc:h2:mem:voting
    user: user
    password: password